
INSERT INTO companies (name) VALUES
    ('Acme Inc.'),
    ('Globex Corporation'),
    ('Initech'),
    ('Umbrella Corporation'),
    ('Stark Industries'),
    ('Wayne Enterprises'),
    ('Oscorp Industries'),
    ('Cyberdyne Systems'),
    ('Wonka Industries'),
    ('Genco Pura Olive Oil Company');

INSERT INTO employees (name, company_id) VALUES
    ('John Doe', 1),
    ('Jane Smith', 1),
    ('Michael Johnson', 1),
    ('Emily Brown', 1),
    ('David Lee', 2),
    ('Sarah Davis', 2),
    ('Robert Wilson', 2),
    ('Jennifer Taylor', 3),
    ('Christopher Anderson', 3),
    ('Jessica Martinez', 3),
    ('Matthew Thomas', 3),
    ('Ashley Moore', 4),
    ('Joshua Jackson', 4),
    ('Amanda White', 4),
    ('Daniel Harris', 5),
    ('Olivia Thompson', 5),
    ('James Martin', 5),
    ('Sophia Garcia', 5),
    ('Andrew Robinson', 6),
    ('Elizabeth Clark', 6),
    ('Joseph Rodriguez', 6),
    ('Victoria Lewis', 7),
    ('William Walker', 7),
    ('Natalie Hall', 7),
    ('Liam Allen', 7),
    ('Ava Young', 8),
    ('Ethan King', 8),
    ('Mia Wright', 8),
    ('Noah Scott', 9),
    ('Isabella Green', 9),
    ('Mason Baker', 9),
    ('Chloe Adams', 9),
    ('Jacob Nelson', 10),
    ('Ella Carter', 10),
    ('Benjamin Mitchell', 10),
    ('Avery Turner', 10),
    ('Scarlett Phillips', 10);